@echo off
echo Running npm install...
call npm install prisma @prisma/client
echo Running prisma generate...
call npx prisma generate
echo Running prisma db push...
call npx prisma db push --accept-data-loss
echo Seeding DB...
node seed.js
echo Starting dev server...
npm run dev
